name: Refresh Yodeck Display

on:
  push:
    branches:
      - main

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Push update to Yodeck
        run: |
          curl -X POST https://app.yodeck.com/api/v1/deviceactions/reboot/640146/ \
            -H "Authorization: Token ${{ secrets.YODECK_API_KEY }}" \
            -H "Content-Type: application/json"
